# simple dataset config

#### for simple scenario
# Info about map [m]
resolution: 0.2
size: 21.0
size_z: 3.0

# default sensor offset from map center [m]
sensor_off_x: -6.0
sensor_off_y: 0
sensor_off_z: -0.5

pose_imu_offset: 0 # yaw offset between "imu" frame and pose estimation

# Bounds on map height
min_z: 0
max_z: 5
